#!/usr/bin/env python3
"""Generate Challenge.lean (the Palomar statement of record) from the development.

Challenge.lean = HEADER
               + the body of B1s/fried_statement_defs_9_14.lean (from its `import Mathlib` on, verbatim)
               + the statement theorem of B1s/fried_counterexample_main.lean with its proof replaced by `sorry`.

Why verbatim: `leanprover/comparator` compares definitions BY VALUE, and Lean's per-module cache of lifted
auxiliary proofs (numerals ⇒ `Nat.AtLeastTwo` instances) means the definitions must appear in the same
module order on both sides. Run after ANY edit to either source file; `--check` exits 1 if Challenge.lean
is stale.
"""
import sys, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFS = ROOT / "B1s" / "fried_statement_defs_9_14.lean"
MAIN = ROOT / "B1s" / "fried_counterexample_main.lean"
OUT = ROOT / "Challenge.lean"
THEOREM = "fried_counterexample_of_resolvent_inputs"

HEADER = """/-
Challenge.lean — the Palomar statement of record for the Fried-program Lean suite.
GENERATED by scripts/make_challenge.py from B1s/fried_statement_defs_9_14.lean and
B1s/fried_counterexample_main.lean — do not edit by hand.

This module imports ONLY Mathlib. It re-declares, verbatim and in the same order, every definition that
appears in the type of the compared theorem (`leanprover/comparator` compares definitions by value between
this environment and `Solution.lean`'s), and then states the theorem with a `sorry`. The development
(`B1s/`) never imports this file; `Solution.lean` re-exports the development, where the same theorem is
proved. Nothing is proved here.

THE MATHEMATICS. On a closed hyperbolic 3-manifold Z with b₁ = 1, take the characters χ_θ and the
conformal family g_τ = e^{−2τb}g_hyp. Near (g_hyp, ρ_triv) the Ruelle resonances near 0 form two small
clusters: a rank-2 cluster in degree 1, encoded by a 2×2 matrix M(θ,τ), and a rank-4 cluster in degree 2,
encoded by a 4×4 matrix A(θ,τ). A BRANCH is one eigenvalue of a cluster matrix followed continuously in
(θ,τ). Degree 1 has the closed branch and the TWIN s_nc(θ,τ), which starts at the double point s*(θ) < 0
and travels at rate r₀ > 0 towards 0. Degree 2 has the two locked branches (the same eigenvalues, lifted
by d₀) and two PURE branches, the roots of Q = X² − e₁X + e₂; the pure branch nearest 0 is z(θ,τ). At the
crossing metric τ = σ(θ) the twin and z reach 0 together, the twin as a pole of ζ and z as a zero, so ζ
stays regular at 0 and ζ(0; g_σ) = τ_R · (rate of the twin)/(rate of z). The twin's rate is at most 2r₀
and z's exceeds 2r₀, so ζ(0; g_σ) ≠ τ_R. Fried's identity would need the two branches to arrive at the
same speed. The whole Lean argument is bookkeeping of these four branches.

THE HYPOTHESES are the properties of the twisted deformed geodesic flow that the argument uses, each
cited to the literature in its docstring (CDDP = Cekić–Delarue–Dyatlov–Paternain, DGRS =
Dang–Guillarmou–Rivière–Shen, BuOl = Bunke–Olbrich, CD = Chaubet–Dang, DR = Dang–Rivière). That the
flow has these properties is taken from those papers and is NOT formalized: the theorem is a conditional
reduction. In particular the cluster matrices are DEFINED here (`Mreal`) as real parts of the frame
matrices A(p)⁻¹B(p) built from contour integrals of matrix elements of two abstract resolvent families;
that these are the cluster matrices of the geodesic flow, and that their imaginary parts vanish, is the
informal identification.
-/
"""

STATEMENT_OPENS = """namespace FriedCrossing

open Filter Topology TwinRate FirstVariation Hadamard OrderCount TorsionCore
  Derived Regularity Ledger Branch

"""

def defs_body() -> str:
    txt = DEFS.read_text()
    i = txt.index("\nimport Mathlib\n") + 1
    return txt[i:]

def theorem_block() -> str:
    lines = MAIN.read_text().split("\n")
    hdr = next(i for i, l in enumerate(lines) if l.startswith(f"theorem {THEOREM}"))
    # walk back over `open … in` / `set_option … in` / docstring lines attached to the theorem
    start = hdr
    while start > 0 and (lines[start-1].rstrip().endswith(" in") or lines[start-1].startswith("/--")
                         or (start-1 < hdr and not lines[start-1].startswith("/--") and _in_docstring(lines, start-1, hdr))):
        start -= 1
    end = next(i for i in range(hdr, len(lines)) if lines[i].rstrip().endswith(":="))
    body = lines[start:end+1]
    return "\n".join(body) + "\n  sorry\n"

def _in_docstring(lines, i, hdr):
    # true if line i lies inside the /-- … -/ docstring immediately preceding hdr
    j = hdr - 1
    while j >= 0 and not lines[j].startswith("/--"):
        if lines[j].rstrip().endswith(" in"):  # passed the attached set_option/open lines
            j -= 1; continue
        if lines[j].rstrip().endswith("-/") or lines[j].strip() and not lines[j].startswith("/--"):
            pass
        j -= 1
    return j <= i <= hdr - 1

def render() -> str:
    return HEADER + defs_body().rstrip("\n") + "\n\n" + STATEMENT_OPENS + theorem_block() + "\nend FriedCrossing\n"

if __name__ == "__main__":
    new = render()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == new
        print("Challenge.lean is", "current" if ok else "STALE — run scripts/make_challenge.py")
        sys.exit(0 if ok else 1)
    OUT.write_text(new)
    n = new.count("\n"); print(f"wrote {OUT.name}: {n} lines, {len(new.encode())} bytes")
